name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [master, preview, dev]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master, preview, dev]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get branch name 
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "TARGET_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "TARGET_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
   
      # Update .env and manifest file with current build time and git sha id to support
      # version handling of the web site to automatically upgrade to latest version faster
      - name: Update git sha and build time
        shell: bash
        run: |
          BUILD_TIME="$(date -u +'%Y-%m-%dT%H:%M:%S')+00:00"
          APIKEY="$(uuidgen)"
          echo Build $BUILD_TIME ${{github.sha}}
          echo Target branch: ${{ env.TARGET_BRANCH }}
          sed -i "s/%REACT_APP_BUILD_TIME%/$BUILD_TIME/g" .env
          sed -i "s/%REACT_APP_BUILD_TIME%/$BUILD_TIME/g" public/manifest.json
          sed -i "s/%REACT_APP_SHA%/${{github.sha}}/g" .env
          sed -i "s/%REACT_APP_SHA%/${{github.sha}}/g" public/manifest.json
          sed -i "s/0624bc00-fcf7-4f31-8f3e-3bdc3eba7ade/$APIKEY/g" src/config.ts
          sed -i "s/0624bc00-fcf7-4f31-8f3e-3bdc3eba7ade/$APIKEY/g" api/config.js
          sed -i "s/TARGET_BRANCH/${{ env.TARGET_BRANCH }}/g" api/config.js
          git log -3 --format=full

      # Build Azure Static Web App and deploy to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_FLOWER_0E8083B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          app_build_command: "npm run test-and-build" # First run some unit tests and then build
          ###### End of Repository/Build Configurations ######
          production_branch: "master"

  # When a pull request is closed, the temporary Azure environment is deleted as well
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_FLOWER_0E8083B03 }}
          action: "close"
